// Verified Nifty 50 Constituents (Sep 2024 Rebalance + Updates)
export const NIFTY_50 = [
    "ADANIENT.NS", "ADANIPORTS.NS", "APOLLOHOSP.NS", "ASIANPAINT.NS", "AXISBANK.NS",
    "BAJAJ-AUTO.NS", "BAJFINANCE.NS", "BAJAJFINSV.NS", "BEL.NS", "BPCL.NS",
    "BHARTIARTL.NS", "BRITANNIA.NS", "CIPLA.NS", "COALINDIA.NS", "DRREDDY.NS",
    "EICHERMOT.NS", "GRASIM.NS", "HCLTECH.NS", "HDFCBANK.NS", "HDFCLIFE.NS",
    "HEROMOTOCO.NS", "HINDALCO.NS", "HINDUNILVR.NS", "ICICIBANK.NS", "ITC.NS",
    "INDUSINDBK.NS", "INFY.NS", "JSWSTEEL.NS", "KOTAKBANK.NS", "LT.NS",
    "M&M.NS", "MARUTI.NS", "NTPC.NS", "NESTLEIND.NS", "ONGC.NS",
    "POWERGRID.NS", "RELIANCE.NS", "SBILIFE.NS", "SBIN.NS", "SHRIRAMFIN.NS",
    "SUNPHARMA.NS", "TCS.NS", "TATACONSUM.NS", "TATAMOTORS.NS", "TATASTEEL.NS",
    "TECHM.NS", "TITAN.NS", "TRENT.NS", "ULTRACEMCO.NS", "WIPRO.NS"
];

// Verified Nifty Next 50 Constituents
// Removed BHARATFORG (Midcap), Added LTIM, DIVISLAB (from Nifty 50)
export const NIFTY_NEXT_50 = [
    "ABB.NS", "ACC.NS", "ADANIENSOL.NS", "ADANIGREEN.NS", "ADANIPOWER.NS", "ATGL.NS",
    "AMBUJACEM.NS", "AWL.NS", "BANKBARODA.NS", "BERGEPAINT.NS", "BHEL.NS",
    "BOSCHLTD.NS", "CANBK.NS", "CHOLAFIN.NS", "COLPAL.NS", "DLF.NS",
    "DABUR.NS", "DIVISLAB.NS", "DMART.NS", "GAIL.NS", "GODREJCP.NS",
    "HAL.NS", "HAVELLS.NS", "HDFCAMC.NS", "ICICIGI.NS", "ICICIPRULI.NS",
    "IOC.NS", "IRCTC.NS", "JINDALSTEL.NS", "JIOFIN.NS", "LICI.NS",
    "LODHA.NS", "LTIM.NS", "MARICO.NS", "MCDOWELL-N.NS", "MOTHERSON.NS",
    "NAUKRI.NS", "PIDILITIND.NS", "PFC.NS", "PGHH.NS", "PNB.NS",
    "RECLTD.NS", "SBICARD.NS", "SHREECEM.NS", "SIEMENS.NS", "SRF.NS",
    "TORNTPHARM.NS", "TVSMOTOR.NS", "VEDL.NS", "ZOMATO.NS"
];

export const NIFTY_100 = [...NIFTY_50, ...NIFTY_NEXT_50];

// Nifty Midcap 100 (Expanded to ~100 stocks to correct Nifty 200 count)
// Contains stocks NOT in Nifty 100
export const NIFTY_MIDCAP_SELECT = [
    // Original Select List Matches
    "ASHOKLEY.NS", "STRAL.NS", "AUROPHARMA.NS", "BALKRISIND.NS", "BANDHANBNK.NS",
    "BANKINDIA.NS", "BATAINDIA.NS", "BHARATFORG.NS", "COFORGE.NS", "CONCOR.NS",
    "CUMMINSIND.NS", "DEEPAKNTR.NS", "DIXON.NS", "ESCORTS.NS", "FEDERALBNK.NS",
    "GODREJPROP.NS", "HINDPETRO.NS", "IDFCFIRSTB.NS", "INDHOTEL.NS", "JSL.NS",
    "JSWENERGY.NS", "JUBLFOOD.NS", "KPITTECH.NS", "LALPATHLAB.NS", "LINDEINDIA.NS",
    "LTTS.NS", "LUPIN.NS", "MAHABANK.NS", "MAXHEALTH.NS", "METROBRAND.NS",
    "MFSL.NS", "MPHASIS.NS", "MRF.NS", "MUTHOOTFIN.NS", "NMDC.NS",
    "OBEROIRLTY.NS", "OFSS.NS", "OIL.NS", "PAGEIND.NS", "PERSISTENT.NS",
    "PETRONET.NS", "PHOENIXLTD.NS", "POLYCAB.NS", "POONAWALLA.NS", "PRESTIGE.NS",
    "RVNL.NS", "SAIL.NS", "SCHAEFFLER.NS", "SOLARINDS.NS", "SONACOMS.NS",
    "SUNDARMFIN.NS", "SUPREMEIND.NS", "SYNGENE.NS", "TATACHEM.NS", "TATACOMM.NS",
    "TATAPOWER.NS", "TIINDIA.NS", "TORNTPOWER.NS", "UNIONBANK.NS", "UNO_MINDA.NS",
    "VBL.NS", "VOLTAS.NS", "WHIRLPOOL.NS", "YESBANK.NS", "ZEEL.NS",
    // New Additions to reach ~100
    "ABCAPITAL.NS", "ALKEM.NS", "APOLLOTYRE.NS", "AUBANK.NS",
    "BIOCON.NS", "BSE.NS", "CGPOWER.NS", "DELHIVERY.NS", "FACT.NS",
    "GICRE.NS", "GLAND.NS", "GMRAIRPORT.NS", "GUJGASLTD.NS", "HUDCO.NS",
    "IDBI.NS", "IGL.NS", "INDIANB.NS", "IPCALAB.NS", "IRFC.NS",
    "KALYANKJIL.NS", "LICHSGFIN.NS", "L&TFH.NS", "MAZDOCK.NS", "NATIONALUM.NS",
    "NHPC.NS", "NYKAA.NS", "PAYTM.NS", "PEL.NS", "POLICYBZR.NS",
    "POWERINDIA.NS", "SJVN.NS", "SUZLON.NS", "TATAELXSI.NS", "UCOBANK.NS", "IRB.NS"
];

// Ensure uniqueness in Nifty 200 (Filter out any accidentally included Nifty 100 stocks from Midcap list)
// Using Set for duplicate removal as requested
const nifty100Set = new Set(NIFTY_100);
const uniqueMidcap = NIFTY_MIDCAP_SELECT.filter(s => !nifty100Set.has(s));

export const NIFTY_200 = [...NIFTY_100, ...uniqueMidcap];
